import React, { useEffect, useState } from "react";
import { getApiError, getReq, putReq } from "../Api";
import { useAuth } from "./AuthContext";
import { useSnackbar } from "notistack";
import Loading from "./Loading";

const Profile = () => {
  const { user, logout } = useAuth(); const { enqueueSnackbar } = useSnackbar();
  const [profile, setProfile] = useState({ first_name: "", last_name: "", patronymic: "", phone_number: "", image: null }); const [preview, setPreview] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!user?.user_id) return; getReq(`users/${user.user_id}/`).then((d) => { setProfile({ first_name: d.first_name || "", last_name: d.last_name || "", patronymic: d.patronymic || "", phone_number: d.phone_number || "", image: null }); setPreview(d.image || ""); }).catch((e) => enqueueSnackbar(getApiError(e, "Не удалось загрузить профиль"), { variant: "error" })).finally(() => setLoading(false)); }, [user, enqueueSnackbar]);
  if (loading) return <Loading />;
  const submit = async (e) => { e.preventDefault(); setSaving(true); const data = new FormData(); Object.entries(profile).forEach(([key, value]) => { if (key !== "image") data.append(key, value); }); if (profile.image) data.append("image", profile.image); try { const updated = await putReq(`users/${user.user_id}/`, data, { headers: { "Content-Type": "multipart/form-data" } }); if (updated.image) setPreview(updated.image); enqueueSnackbar("Профиль сохранён", { variant: "success" }); } catch (err) { enqueueSnackbar(getApiError(err, "Не удалось сохранить профиль"), { variant: "error" }); } finally { setSaving(false); } };
  return <main className="account-page"><div className="account-head"><div><div className="section-kicker">ACCOUNT</div><h1>Личный кабинет</h1></div><button className="button button-ghost" onClick={logout}>Выйти</button></div><form className="profile-card" onSubmit={submit}><div className="profile-aside"><div className="big-avatar">{preview ? <img src={preview} alt="Аватар" /> : (profile.first_name?.[0] || user.email?.[0] || "U").toUpperCase()}</div><label className="button button-outline">Изменить фото<input type="file" accept="image/*" hidden onChange={(e) => { const file = e.target.files?.[0]; if (file) { setProfile((p) => ({ ...p, image: file })); setPreview(URL.createObjectURL(file)); } }} /></label><span className="muted">JPG, PNG или WEBP</span></div><div className="form-grid">{[["last_name","Фамилия",true],["first_name","Имя",true],["patronymic","Отчество",false],["phone_number","Телефон",false]].map(([name,label,required]) => <label className="field" key={name}><span>{label}</span><input name={name} value={profile[name]} required={required} onChange={(e) => setProfile((p) => ({ ...p, [name]: e.target.value }))} /></label>)}<div className="form-actions"><button className="button button-primary" disabled={saving}>{saving ? "Сохраняем…" : "Сохранить изменения"}</button></div></div></form></main>;
};
export default Profile;
