# Generated by Django 5.1.1 on 2024-09-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0002_customuser_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_year', models.TextField()),
                ('os_version', models.TextField()),
                ('screen_size', models.TextField()),
                ('screen_res', models.TextField()),
                ('screen_type', models.TextField()),
                ('screen_fps', models.TextField()),
                ('ram_size', models.TextField()),
                ('ram_type', models.TextField()),
                ('rom_size', models.TextField()),
                ('rom_type', models.TextField()),
                ('camera_count', models.TextField()),
                ('main_camera_mp', models.TextField()),
                ('camera_type', models.TextField()),
                ('camera_block', models.TextField()),
                ('max_video_resolution', models.TextField()),
                ('front_camera_mp', models.TextField()),
                ('cpu', models.TextField()),
                ('tech_process', models.TextField()),
                ('gpu', models.TextField()),
                ('edges_material', models.TextField()),
                ('back_material', models.TextField()),
                ('back_color', models.TextField()),
                ('protection', models.TextField()),
                ('length', models.TextField()),
                ('width', models.TextField()),
                ('thickness', models.TextField()),
                ('weight', models.TextField()),
                ('screen_ratio', models.TextField()),
                ('screen_protector', models.TextField()),
                ('color_count', models.TextField()),
                ('ppi', models.TextField()),
                ('accum_type', models.TextField()),
                ('accum_volume', models.TextField()),
                ('charging_power', models.TextField()),
                ('wireless_charging', models.TextField()),
                ('bluetooth', models.TextField()),
                ('audio_port', models.TextField()),
                ('charge_port', models.TextField()),
                ('wifi', models.TextField()),
                ('nfc', models.TextField()),
                ('_5g', models.TextField()),
                ('sim_count', models.TextField()),
                ('sim_type', models.TextField()),
            ],
        ),
    ]
