# Generated by Django 5.1.1 on 2024-09-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0003_smartphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='front_camera_aperture',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
