# Generated by Django 5.1.1 on 2024-09-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0004_smartphone_front_camera_aperture'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='price',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smartphone',
            name='title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
