# Generated by Django 5.1.1 on 2024-09-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0005_smartphone_image_url_smartphone_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='_5g',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='nfc',
            field=models.BooleanField(),
        ),
    ]
