# Generated by Django 5.1.1 on 2024-09-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0006_alter_smartphone__5g_alter_smartphone_nfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartphone',
            name='image_url',
            field=models.TextField(),
        ),
    ]
