# Generated by Django 5.2.15 on 2026-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_matcher_app', '0009_customuser_image_basketitem_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartphone',
            name='_5g',
        ),
        migrations.AddField(
            model_name='smartphone',
            name='has_5g',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='default_user.svg', upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accum_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accum_volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Емкость батареи (mAh)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='audio_port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='back_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='back_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='bluetooth',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='brand',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_block',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='camera_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='charge_port',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='charging_power',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='color_count',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='cpu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='edges_material',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='front_camera_aperture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='front_camera_mp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='gpu',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='launch_year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_camera_mp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='max_video_resolution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='nfc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='os_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ppi',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='protection',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ОЗУ (ГБ)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='rom_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ПЗУ (ГБ)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='rom_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_fps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_protector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_ratio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_res',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_size',
            field=models.FloatField(blank=True, null=True, verbose_name='Диагональ экрана'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='screen_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sim_count',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sim_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='tech_process',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='wifi',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='wireless_charging',
            field=models.BooleanField(default=False),
        ),
    ]
